# Generated by Django 3.1.7 on 2021-03-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.tag')),
                ('accommodation_type', models.CharField(max_length=100)),
            ],
            bases=('api.tag',),
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.tag')),
                ('location_name', models.CharField(max_length=100)),
            ],
            bases=('api.tag',),
        ),
        migrations.CreateModel(
            name='TransportationTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.tag')),
                ('transport_type', models.CharField(max_length=100)),
            ],
            bases=('api.tag',),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_title', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('duration_magnitude', models.IntegerField()),
                ('tag', models.ManyToManyField(to='api.Tag')),
            ],
        ),
    ]
