# Generated by Django 3.1.7 on 2021-03-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itinerary_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtag',
            name='tag_ptr',
        ),
        migrations.RemoveField(
            model_name='transportationtag',
            name='tag_ptr',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='tag',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='transportation_tag',
            field=models.TextField(choices=[('CAR', 'Car'), ('TRAIN', 'Trn'), ('PLANE', 'Pln'), ('MOTORCYCLE', 'Mtr'), ('BICYCLE', 'Cyc')], default=''),
        ),
        migrations.DeleteModel(
            name='AccommodationTag',
        ),
        migrations.DeleteModel(
            name='LocationTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TransportationTag',
        ),
    ]
