# Generated by Django 3.1.7 on 2021-03-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210315_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='transportation_tag',
            field=models.TextField(choices=[('Car', 'Car'), ('Train', 'Train'), ('Plane', 'Plane'), ('Motorcycle', 'Motorcycle'), ('Bicycle', 'Bicycle')], default=''),
        ),
    ]
